import type { User } from "./types";

export const initialUsersData: User[] = [
  {
    id: 1,
    name: "Olivia Martinez",
    email: "olivia.martinez@company.com",
    avatar: "OM",
    role: "Admin",
    plan: "Enterprise",
    billing: "Credit Card",
    status: "Active",
    joinedDate: "2024-01-10",
    lastLogin: "2025-01-15",
  },
  {
    id: 2,
    name: "James Wilson",
    email: "james.wilson@company.com",
    avatar: "JW",
    role: "Editor",
    plan: "Professional",
    billing: "Auto Debit",
    status: "Active",
    joinedDate: "2024-03-22",
    lastLogin: "2025-01-14",
  },
  {
    id: 3,
    name: "Sophie Chen",
    email: "sophie.chen@company.com",
    avatar: "SC",
    role: "Author",
    plan: "Basic",
    billing: "Paypal",
    status: "Pending",
    joinedDate: "2024-05-01",
    lastLogin: "2025-01-12",
  },
  {
    id: 4,
    name: "Marcus Johnson",
    email: "marcus.johnson@company.com",
    avatar: "MJ",
    role: "Maintainer",
    plan: "Professional",
    billing: "UPI",
    status: "Suspended",
    joinedDate: "2023-11-18",
    lastLogin: "2024-12-30",
  },
  {
    id: 5,
    name: "Emma Thompson",
    email: "emma.thompson@company.com",
    avatar: "ET",
    role: "Subscriber",
    plan: "Basic",
    billing: "Credit Card",
    status: "Inactive",
    joinedDate: "2023-09-05",
    lastLogin: "2024-10-01",
  },
];
