import {
  HOME_PAGE,
  NEXT_CHAT_ENDPOINT,
  WEB_DASHBOARD_ENDPOINT,
  WEB_TICKET_ENDPOINT,
  WEB_TICKET_MY_TICKET_ENDPOINT,
} from "./web";

export const WEB_PRIVATE_ROUTE = [
  HOME_PAGE,
  WEB_DASHBOARD_ENDPOINT,
  WEB_TICKET_ENDPOINT,
  WEB_TICKET_MY_TICKET_ENDPOINT,
  NEXT_CHAT_ENDPOINT,
];
